### ISSUE TITLE
Record normal login activity, so you know when an attacks happening 

### ISSUE THREAD

**Issue by TomLewis** [BlackDemonZyT/BotSentry#35]
Super simple, all you have to do is record normal login activity, so if a server normally has 3 logins a second, or a server only had 1 login every hour each database will be tailored to the server it's running on, by keeping a simple log of normal data it's extremely simple to then detect oddities if a mass surge of people connect at once.

**Comment by Laurenshup** [comment]
Actually that was the idea behind the latest check (detection.slowattack.spike). However this has to be made like you described, that check just looks at the last two hours. But it should make notes about the hour of the day etc.

**Comment by TomLewis** [comment]
Yeah, I have a mostly US based community, so it gets more busy when they wake up/get home from work/school.
It also changes on weekends and Fridays, also completely changes different times of the year based on holidays around the world.
It also changes if were holding an event, or if the servers having issues.

Many variables here. 

A really good developer to look at is the guy that makes Plan, he records analytics for large quantities of data, you might also look into working with that, as he's already recorded every login event already, no need for it twice, I have years and years and years of login/out data. You could even use your attack data to work with plan data so you can check when you 100% there was a bot attack against the plan data for reference.

**Comment by Laurenshup** [comment]
Due to the big data usage, this will take a while to code. This might be released this year.

**Comment by Laurenshup** [comment]
Looking back into this, although this seems like a good idea. Only if very suddenly a lot of players join, it could mean they are bots. There are quite some variables to look into this, and this would definitely need hooking into some kind of session tracking. Although Plan could work, we do not want to depend on other plugins, as we would like to be a standalone plugin. To do something like this, either BotSentry has to track it, or a custom plugin could hook into BotSentry's API.

But has said before, even seeing that more players join, cannot guarantee that they are actually bots. Since we use an AntiProxy system, I believe coding above features, are not really an improvement over already existing systems.
